name: camperboss
description: Premium Flutter app for camper, vanlife, and motorhome travel planning.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  geolocator: ^14.0.3
  http: ^1.6.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
